# Generated by Django 4.2 on 2023-06-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_password_post_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('GE', 'General'), ('TE', 'Technology'), ('BE', 'Beauty'), ('FA', 'Fashion'), ('AG', 'Agony Aunt')], default='GE', max_length=2),
        ),
    ]
